days-before-stale: 45
days-before-close-stale: 7

issues:
  label-to-add: stale
  exempt-labels: ['pinned', 'security']

prs:
  label-to-add: stale
  exempt-labels: ['work in progress']

exempt-all-milestones: true
